# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27c98db7bd4eb54c956bdad83dbb127b190e89b502a15a7e033b8880282e61e302f4e8b2e81f009e4b7dcf644823dc41a8a57ee6cf3f07f8d0623625416aa7ef

test:
  secret_key_base: 71934a9ba8187f03ef841e9aedf00c4d7dda82ccb3bbe1e134c530ba5c508d0c6f22c56e328dc5193eba94eb27c5306cef061de4dae6bcc9dea801e40e226a31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
